CREATE TABLE COMMENT (ID INTEGER NOT NULL, TEXT VARCHAR(240) NOT NULL, AUTHOR_ID INTEGER, POST_ID INTEGER, PRIMARY KEY (ID));
CREATE TABLE POST (ID INTEGER NOT NULL, TEXT VARCHAR(500) NOT NULL, TITLE VARCHAR(60) UNIQUE, AUTHOR_ID INTEGER, PRIMARY KEY (ID));
CREATE TABLE USER (ID INTEGER NOT NULL, FULLNAME VARCHAR(255), HASHEDPASSWORD VARCHAR(120) NOT NULL, USERNAME VARCHAR(16) UNIQUE, PRIMARY KEY (ID));
ALTER TABLE COMMENT ADD CONSTRAINT FK_COMMENT_POST_ID FOREIGN KEY (POST_ID) REFERENCES POST (ID);
ALTER TABLE COMMENT ADD CONSTRAINT COMMENT_AUTHOR_ID FOREIGN KEY (AUTHOR_ID) REFERENCES USER (ID);
ALTER TABLE POST ADD CONSTRAINT FK_POST_AUTHOR_ID FOREIGN KEY (AUTHOR_ID) REFERENCES USER (ID);
CREATE TABLE SEQUENCE (SEQ_NAME VARCHAR(50) NOT NULL, SEQ_COUNT DECIMAL(15), PRIMARY KEY (SEQ_NAME));
INSERT INTO SEQUENCE(SEQ_NAME, SEQ_COUNT) values ('SEQ_GEN', 0);
