ALTER TABLE COMMENT DROP CONSTRAINT FK_COMMENT_POST_ID
ALTER TABLE COMMENT DROP CONSTRAINT COMMENT_AUTHOR_ID
ALTER TABLE POST DROP CONSTRAINT FK_POST_AUTHOR_ID
DROP TABLE COMMENT
DROP TABLE POST
DROP TABLE USER
DELETE FROM SEQUENCE WHERE SEQ_NAME = 'SEQ_GEN'
